{"name": "Вход с недостаточными данными", "status": "failed", "statusDetails": {"message": "AssertionError: assert (504 == 400)\n +  where 504 = <Response [504]>.status_code", "trace": "self = <test_courier.TestCourierLoginAPI object at 0x00000201BD3E92E0>, user_data = {'login': 'test_login_1789'}\n\n    @allure.description('Проверяем попытку входа с отправкой недостаточных данных')\n    @allure.title('Вход с недостаточными данными')\n    @pytest.mark.parametrize('user_data', (TestCourier.login_empty_login, TestCourier.login_empty_password, TestCourier.login_only_password, TestCourier.login_only_login))\n    def test_courier_login_no_data_fail(self, user_data):\n        r = requests.post(TestAPICourierLinks.main_url + TestAPICourierLinks.login_url, data=user_data)\n    \n>       assert r.status_code == 400 and r.json()['message'] == CourierErrors.error_login_no_data\nE       assert (504 == 400)\nE        +  where 504 = <Response [504]>.status_code\n\ntests\\test_courier.py:63: AssertionError"}, "description": "Проверяем попытку входа с отправкой недостаточных данных", "parameters": [{"name": "user_data", "value": "{'login': 'test_login_1789'}"}], "start": 1736846657335, "stop": 1736846717605, "uuid": "8ac69ced-dde2-4cc4-8191-7aff72cdb800", "historyId": "1d5dd992a78d294841385c37a294ee4f", "testCaseId": "9d10fbc3585789bb29ad092d3d064fa0", "fullName": "tests.test_courier.TestCourierLoginAPI#test_courier_login_no_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierLoginAPI"}, {"name": "host", "value": "LAPTOP-B6TT34TV"}, {"name": "thread", "value": "17268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}